config/routes.rb
MusicApp::Application.routes.draw do
  root to: "bands#index" #always root to a GET request page
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:create, :destroy, :new]
  
  resources :bands, only: [:index, :create, :new, :edit, :update, :destroy]
  resources :bands, only: [:show] do
    resources :albums, only: [:new]
  end
  resources :albums, only: [:create, :edit, :update, :destroy]
  resources :albums, only: [:show] do
    resources :tracks, only: [:new]
  end
  resources :tracks, only: [:create, :edit, :show, :update, :destroy]
  resources :notes, only: [:create, :destroy]
end

app/models/note.rb
class Note < ActiveRecord::Base
  
  validates :description, presence: true
  
  belongs_to :track
  
  belongs_to :user
  
  
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  
  before_action :require_user!, only: [:destroy]
  
  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id
    @note.save
    flash.now[:errors] = @note.errors.full_messages
    redirect_to track_url(@note.track_id)
  end
  
  def destroy
    @note = Note.find(params[:id])
    if @note.user_id != current_user.id
      render text: "Can only destroy your own note", status: :forbidden
    else
      @note.destroy
      redirect_to track_url(@note.track_id)
    end
  end
  
  def note_params
    params.require(:note).permit(:description, :track_id)
  end
  
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_index.html.erb
<strong> Notes </strong>
<br>
<br>
  <% notes.each do |note| %>
     <label> <%= note.user.email %> writes: </label>
     <p> <%= note.description %> </p>
	 <% if current_user.id == note.user_id %>
	   <%= button_to "Delete note", note_url(note), method: :delete %>
	 <%end%>
  <%end%>

app/views/notes/_new.html.erb
<form action="<%= notes_url %>" method="POST">
  
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  
  <input type="hidden" name="note[track_id]" value="<%= track.id %>">
  
  <label> Post a note. </label>
  <br>
  <textarea name="note[description]"></textarea>
  <br>
  
  <input type="submit" value="Submit note.">
</form>