config/routes.rb
MusicApp::Application.routes.draw do
  root to: "bands#index" #always root to a GET request page
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:create, :destroy, :new]
  
  resources :bands, only: [:index, :create, :new, :edit, :update, :destroy]
  resources :bands, only: [:show] do
    resources :albums, only: [:new]
  end
  resources :albums, only: [:create, :edit, :update, :destroy]
  resources :albums, only: [:show] do
    resources :tracks, only: [:new]
  end
  resources :tracks, only: [:create, :edit, :show, :update, :destroy]
  resources :notes, only: [:create, :destroy]
end

app/models/track.rb
class Track < ActiveRecord::Base
  
  belongs_to :album
  
  has_one :band, through: :album, source: :band
  
  has_many :notes
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  
  before_action :require_user!
  
  def new
    album = Album.find(params[:album_id]) #why does it come back as album_id, instead of params[:album][:id]?
    @track = album.tracks.new
    render :new
  end
  
  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end
  
  def show
    @track = Track.find(params[:id])
    render :show
  end
  
  #make sure to redirect after each controller action
  def destroy
    @track = Track.find(params[:id])
    @track.destroy
    redirect_to track_url(@track.track_id)
  end
  
  def edit
    @track = Track.find(params[:id])
    render :edit
  end
  
  def update
    @track = Track.find(params[:id])
    if @track.update(track_params)
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :edit
    end
  end
  
  def track_params
    params.require(:track).permit(:name, :album_id, :track_type, :lyrics)
  end
  
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/tracks/_form.html.erb
<% action = (track.persisted? ? track_url(track) : tracks_url) %>
<% method = (track.persisted? ? :patch : :post) %>

<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
	
<label for="name"> Name </label>
<input type="text" name="track[name]" id="name" value="<%= track.name %>">
<br>

<label for="band">Album</label>
<select name="track[album_id]" id="album">
	<option></option>
	<% Album.all.each do |album| %>
	  <option
	    <%= album.id == track.album_id ? "selected" : "" %>
	    value="<%= album.id %>">
	    <%= album.name %>
	  </option>
	<% end %>
</select>
<br>

<label> Track Type </label>
  <input
    type="radio"
    name="track[track_type]"
    value="Bonus"
    id="bonus"
    <%= track.track_type == "Bonus" ? "checked" : "" %>>
  <label for="bonus">Bonus</label>
  <input
    type="radio"
    name="track[track_type]"
    value="Regular"
    id="regular"
    <%= track.track_type == "Regular" ? "checked" : "" %>>
  <label for="regular">Regular</label>
  <br>
  
  <label>
     Lyrics
     <textarea name="track[lyrics]"><%= track.lyrics %></textarea>
  </label>
  <br>

 <% submit_text = (track.persisted? ? 'Update' : 'Create') + ' track' %>
  <input type="submit" value="<%= submit_text %>">
</form>

app/views/tracks/edit.html.erb
<h1> Edit Track </h1>

<%= render "form", track: @track %>

app/views/tracks/new.html.erb
<h1> New Track </h1>

<%= render "form", track: @track %>

app/views/tracks/show.html.erb
<h1> <%= @track.name%> </h1>

<%= link_to "Back to tracks list", album_url(@track.album_id)%>

<ul>
    <li> Band: <%= link_to @track.band.name, band_url(@track.band) %> </li>
	<li> Album: <%= link_to @track.album.name, album_url(@track.album) %> </li>
	<li> Type: <%= @track.track_type %></li>
	<li> Lyrics: <%= ugly_lyrics(@track.lyrics) %> </li>
</ul>

<%= render "notes/index", notes: @track.notes %>

<%= render "notes/new", track: @track %>

<%= link_to "Edit track", edit_track_url(@track) %>
<%= link_to "Delete track", track_url(@track), method: :delete%>
<%= link_to "Add new track", new_album_track_url(@track.album_id) %>