config/routes.rb
MusicApp::Application.routes.draw do
  root to: "bands#index" #always root to a GET request page
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:create, :destroy, :new]
  
  resources :bands, only: [:index, :create, :new, :edit, :update, :destroy]
  resources :bands, only: [:show] do
    resources :albums, only: [:new]
  end
  resources :albums, only: [:create, :edit, :update, :destroy]
  resources :albums, only: [:show] do
    resources :tracks, only: [:new]
  end
  resources :tracks, only: [:create, :edit, :show, :update, :destroy]
  resources :notes, only: [:create, :destroy]
end

app/models/album.rb
class Album < ActiveRecord::Base
  
  belongs_to :band
  
  has_many :tracks, dependent: :destroy
  
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  
  before_action :require_user!
  
  def new
    band = Band.find(params[:band_id])
    @album = band.albums.new
    render :new
  end
  
  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end
  
  def show
    @album = Album.find(params[:id])
    render :show
  end
  
  #make sure to redirect after each controller action
  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to band_url(@album.band_id)
  end
  
  def edit
    @album = Album.find(params[:id])
    render :edit
  end
  
  def update
    @album = Album.find(params[:id])
    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end
  
  def album_params
    params.require(:album).permit(:name, :band_id, :album_type)
  end
  
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<% action = (album.persisted? ? album_url(album) : albums_url) %>
<% method = (album.persisted? ? :patch : :post) %>

<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
	
<label for="name"> Name </label>
<input type="text" name="album[name]" id="name" value="<%= album.name %>">
<br>

<label for="band">Band</label>
<select name="album[band_id]" id="band">
	<option></option>
	<% Band.all.each do |band| %>
	  <option
	    <%= band.id == album.band_id ? "selected" : "" %>
	    value="<%= band.id %>">
	    <%= band.name %>
	  </option>
	<% end %>
</select>
<br>

<label> Album Type </label>
  <input
    type="radio"
    name="album[album_type]"
    value="Live"
    id="live"
    <%= album.album_type == "Live" ? "checked" : "" %>>
  <label for="live">Live</label>
  <input
    type="radio"
    name="album[album_type]"
    value="Studio"
    id="studio"
    <%= album.album_type == "Studio" ? "checked" : "" %>>
  <label for="studio">Studio</label>
  <br>

 <% submit_text = (album.persisted? ? 'Update' : 'Create') + ' album' %>
  <input type="submit" value="<%= submit_text %>">
</form>

app/views/albums/edit.html.erb
<h1> Edit Album </h1>

<%= render "form", album: @album %>

app/views/albums/new.html.erb
<h1> New Album </h1>

<%= render "form", album: @album %>

app/views/albums/show.html.erb
<h1> <%= @album.name%> </h1>

<%= link_to "Back to albums list", band_url(@album.band_id)%>

<ul>
	<li> Band: <%= link_to @album.band.name, band_url(@album.band) %> </li>
	<li> Type: <%= @album.album_type %> </li>
</ul>

<label> Tracks </label>
<ul>
    <% @album.tracks.each do |track| %>
      <li> <%= link_to track.name, track_url(track) %> </li>
    <%end%>
</ul>

<%= link_to "Edit album", edit_album_url(@album) %>
<%= link_to "Delete album", album_url(@album), method: :delete%>
<%= link_to "Add new track", new_album_track_url(@album) %>