config/routes.rb
MusicApp::Application.routes.draw do
  root to: "bands#index" #always root to a GET request page
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:create, :destroy, :new]
  
  resources :bands, only: [:index, :create, :new, :edit, :update, :destroy]
  resources :bands, only: [:show] do
    resources :albums, only: [:new]
  end
  resources :albums, only: [:create, :edit, :update, :destroy]
  resources :albums, only: [:show] do
    resources :tracks, only: [:new]
  end
  resources :tracks, only: [:create, :edit, :show, :update, :destroy]
  resources :notes, only: [:create, :destroy]
end

app/models/band.rb
class Band < ActiveRecord::Base
  
  has_many :albums, dependent: :destroy #only used after has_many
  
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  
  before_action :require_user!
  
  def index
    @bands = Band.all
    render :index
  end
  
  def new
    @band = Band.new
    render :new
  end
  
  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end
  
  def show
    @band = Band.find(params[:id])
    render :show
  end
  
  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end
  
  def edit
    @band = Band.find(params[:id])
    render :edit
  end
  
  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end
  
  def band_params
    params.require(:band).permit(:name)
  end
  
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_form.html.erb
<% action = (band.persisted? ? band_url(band) : bands_url) %>
<% method = (band.persisted? ? :patch : :post) %>

<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
	
<label for="name"> Name </label>
<input type="text" name="band[name]" id="name" value="<%= band.name %>">

 <% submit_text = (band.persisted? ? 'Update' : 'Create') + ' band' %>
  <input type="submit" value="<%= submit_text %>">
</form>

app/views/bands/edit.html.erb
<h1> Edit Band </h1>

<%= render "form", band: @band %>

app/views/bands/index.html.erb
<h1> All Bands </h1>
<ul>
  <% @bands.each do |band| %>
    <li> <%= link_to band.name, band_url(band) %> </li>
  <%end%>
</ul>

<%= link_to "Add a band", new_band_url %>

app/views/bands/new.html.erb
<h1> New Band </h1>

<%= render "form", band: @band %>

app/views/bands/show.html.erb
<h1> <%= @band.name%> </h1>

<%= link_to "Back to bands list", bands_url%>

<ul>
  <% @band.albums.each do |album| %>
    <li> <%= link_to album.name, album_url(album) %> </li>
  <%end%>
</ul>

<%= link_to "Edit band", edit_band_url(@band) %>
<%= link_to "Delete band", band_url(@band), method: :delete%>
<%= link_to "Add new album", new_band_album_url(@band) %>